NikolaySavenko/domus-sapiens

- README.md
> docs(design): add figma links to readme - #13

- README.md
> feat(design): add link to figma

- README.md
> feat(design): add link to Logo - #54

- docker-compose.yml
> fix(compose): forward service ports and setup services env - #55

- DomusSapiensBackend/FrontendService/Controllers/Actions.cs
- DomusSapiensBackend/FrontendService/FrontendService.csproj
- DomusSapiensBackend/FrontendService/Messages/ActionMessage.cs
- DomusSapiensBackend/FrontendService/Messages/IMessage.cs
> feat(controllers): add send message to iot via controller - #53 

- DomusSapiensBackend/FrontendService/Dockerfile
- DomusSapiensBackend/FrontendService/FrontendService.csproj
> fix(docker): correct build - #76

- DomusSapiensBackend/DomusSapiensBackend.sln
- DomusSapiensBackend/FrontendService/Controllers/Actions.cs
- DomusSapiensBackend/FrontendService/FrontendService.csproj
- DomusSapiensBackend/FrontendService/Messages/ActionMessage.cs
- DomusSapiensBackend/FrontendService/Model/PostgresContext.cs
- DomusSapiensBackend/FrontendService/Program.cs
- DomusSapiensBackend/docker-compose.dcproj
- DomusSapiensBackend/docker-compose.override.yml
- DomusSapiensBackend/docker-compose.yml
> fix(controller): correct actions controller logic - #80

- .gitignore
> feat(gitignore): add .env file to build docker-compose.yml in .gitignore #82

- docker-compose.yml
> fix(docker-compose): fix database connection with Frontend API - #91

- .github/workflows/build-frontend-server.yml
- Frontend/package.json
- README.md
> feat(frontend server): write GitHub action to build frontend server - #78

- DomusSapiensBackend/FrontendService/Controllers/Actions.cs
- DomusSapiensBackend/FrontendService/Program.cs
> fix(rest): add rest options - #94 

- Frontend/src/components/CompositionComponent.vue
- Frontend/src/layouts/MainLayout.vue
- Frontend/src/pages/index.vue
- Frontend/src/pages/information.vue
- Frontend/src/router/index.ts
> feat(quasar): added the ability to send requests-#71

- Frontend/src/css/quasar.variables.scss
- Frontend/src/layouts/MainLayout.vue
- Frontend/src/pages/index.vue
- Frontend/src/pages/information.vue
- Frontend/src/pages/mydevice.vue
- Frontend/src/pages/profile.vue
> fix(design): updated the design of the pages

- Frontend/src/components/CompositionComponent.vue
- Frontend/src/pages/index.vue
- Frontend/src/pages/information.vue
> fix(api): change adress

- Frontend/quasar.conf.js
- Frontend/src/pages/index.vue
> fix(quasar): remove the hash from the path

- DomusSapiensBackend/FrontendService/Controllers/Actions.cs
- DomusSapiensBackend/FrontendService/Controllers/Users.cs
> fix(controllers): replace where first to first or default - #85

- DomusSapiensBackend/IoTControlService/IoTControlService.csproj
- DomusSapiensBackend/IoTControlService/Program.cs
> feat(log): use serilog in iot control - #108

- DomusSapiensBackend/IoTControlService/ServiceBusMessaging/HighLevelCommendsConsumer.cs
- DomusSapiensBackend/IoTControlService/ServiceBusMessaging/IoTQueueConsumer.cs
- DomusSapiensBackend/IoTControlService/ServiceBusMessaging/ProcessData.cs
> fix(exceptions): add exceptions handling in iot control - #110

- DomusSapiensBackend/FrontendService/Controllers/Actions.cs
- DomusSapiensBackend/FrontendService/Controllers/Users.cs
> fix(controllers): add not found support - #112

- DomusSapiensBackend/FrontendService/Controllers/Actions.cs
- DomusSapiensBackend/FrontendService/Messages/ActionMessage.cs
- DomusSapiensBackend/IoTControlService/IoTControlService.csproj
- DomusSapiensBackend/IoTControlService/Model/Command/Command.cs
- DomusSapiensBackend/IoTControlService/Model/Command/CommandFactory.cs
- DomusSapiensBackend/IoTControlService/Model/Command/IExecutable.cs
- DomusSapiensBackend/IoTControlService/Model/DeviceMethods/GPIOSwitch.cs
- DomusSapiensBackend/IoTControlService/Model/DeviceMethods/IDeviceMethod.cs
- DomusSapiensBackend/IoTControlService/Model/HighLevelAction/HighLevelAction.cs
- DomusSapiensBackend/IoTControlService/ServiceBusMessaging/HighLevelCommendsConsumer.cs
- DomusSapiensBackend/IoTControlService/ServiceBusMessaging/IoTQueueConsumer.cs
- DomusSapiensBackend/IoTControlService/ServiceBusMessaging/ProcessData.cs
> feat(iot): invoke controller by cloud

- docker-compose.yml
> feat(docker-compose): add enviroment variable for IoTControl Service - #114

- Frontend/src/components/CompositionComponent.vue
- Frontend/src/layouts/MainLayout.vue
- Frontend/src/pages/information.vue
> fix(quasar): add new button click animations

- .github/workflows/deploy-frontend-server.yml
> feat(deploy frontend server): done github action to deploy frontend server - #95

- Frontend/src/components/CompositionComponent.vue
- Frontend/src/pages/index.vue
- Frontend/src/pages/information.vue
> fix(quasar): fix bug with button

- DomusSapiensBackend/IoTControlService/Model/Command/CommandFactory.cs
- DomusSapiensBackend/IoTControlService/Model/DeviceMethods/GPIOSwitch.cs
- DomusSapiensBackend/IoTControlService/Model/DeviceMethods/IDeviceMethod.cs
> fix: correct send json - #123
